// File generated by FlutterFire CLI & configured for UECFI Portal Management.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.windows:
        return windows;
      default:
        return android;
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-65P4ZHRTP6Lw1F1fb6xkRxwqajKHGdY',
    appId: '1:1001157137185:android:cde7a4709224885a986460',
    messagingSenderId: '1001157137185',
    projectId: 'uecfi-portal-167a5',
    storageBucket: 'uecfi-portal-167a5.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-65P4ZHRTP6Lw1F1fb6xkRxwqajKHGdY',
    appId: '1:1001157137185:android:cde7a4709224885a986460',
    messagingSenderId: '1001157137185',
    projectId: 'uecfi-portal-167a5',
    storageBucket: 'uecfi-portal-167a5.firebasestorage.app',
  );
}
